In [1]:
from numpy import array, roots
import numpy as np
a = [[1, 0], [6, 7], [7, -8], [2, 1]]
v = array(a)
v


array([[ 1,  0],
       [ 6,  7],
       [ 7, -8],
       [ 2,  1]])

In [6]:
def compute(v, x):
    return array([(v[:, i]-x[i])**2 for i in range(v.shape[1])])


def Dist(v, x):
    return compute(v, x).sum(axis=0)**0.5


def Findmin(distance):
    mn = [0, 1]
    for i in range(len(distance)):
        for j in range(i+1, len(distance)):
            if distance[mn[0]][mn[1]] > distance[i][j]:
                mn = [i, j]
    return mn


def DoComp(v, distance):
    c = Findmin(distance)
    v[c[0]] = (v[c[0]]+v[c[1]])/2
    v = np.delete(v, c[1], axis=0)
# print((compute((1, 2)).sum(axis=0))**0.5)


In [3]:
v = np.array([[2, 10], [2, 5], [8, 4], [5, 8], [7, 5]], dtype=float)
distance = array([Dist(v,v[i]) for i in range(len(v))])
distance


array([[0.        , 5.        , 8.48528137, 3.60555128, 7.07106781],
       [5.        , 0.        , 6.08276253, 4.24264069, 5.        ],
       [8.48528137, 6.08276253, 0.        , 5.        , 1.41421356],
       [3.60555128, 4.24264069, 5.        , 0.        , 3.60555128],
       [7.07106781, 5.        , 1.41421356, 3.60555128, 0.        ]])

In [7]:
v = array([[2, 2], [2, -2], [-2, 2], [-2, -2],
          [-1, 1], [1, -1], [-1, -1], [1, 1]])
Dist(v, (0, 0))


array([2.82842712, 2.82842712, 2.82842712, 2.82842712, 1.41421356,
       1.41421356, 1.41421356, 1.41421356])