In [2]:
import numpy as np
X=np.array([2,3,2,3,3,21])
print(X,type(X))

[ 2  3  2  3  3 21] <class 'numpy.ndarray'>


In [4]:
a=np.arange(23)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [6]:
s=slice(2,15,2)
print(a[s])

[ 2  4  6  8 10 12 14]


In [17]:
!pip install pandas --quiet
import pandas  as pd

In [13]:
d={'a':[2,3,3,4,5],'b':[2,2,4,5,6]}
pd.DataFrame(d)

a  b
0  2  2
1  3  2
2  3  4
3  4  5
4  5  6

In [15]:
!python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 660.6 kB/s eta 0:00:04
   - -------------------------------------- 0.1/2.1 MB 558.5 kB/s eta 0:00:04
   - -------------------------------------- 0.1/2.1 MB 655.4 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/2.1 MB 1.1 MB/s eta 0:00:02
   ------ --------------------------------- 0.3/2.1 MB 1.2 MB/s eta 0:00:02
   ------ --------------------------------- 0.3/2.1 MB 1.2 MB/s eta 0:00:02
   ------ --------------------------------- 0.3/2.1 MB 1.2 MB/s eta 0:00:02
   ------ --------------------------------- 0.4/2.1 MB 916.6 kB/s eta 0:00:02
   -------- ------------------------------- 0.4/2.1 MB 1.0 MB/s eta 0:00:02
   ---------- ----------------------------- 0.5/2.1 MB 1.1 MB/s eta 0:00:02
   ---------- --

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [16]:
d={'a':[2,3,3,4,5],'b':[2,2,4,5,6]}
pd.DataFrame(d,index=list('abcde'))

a  b
a  2  2
b  3  2
c  3  4
d  4  5
e  5  6

In [22]:
d={'a':[2,3,3,4,5],'b':[2,2,4,5,6]}
pd.DataFrame.from_dict(d,orient='index'),pd.DataFrame.from_dict(d,orient='columns')

(   0  1  2  3  4
 a  2  3  3  4  5
 b  2  2  4  5  6,
    a  b
 0  2  2
 1  3  2
 2  3  4
 3  4  5
 4  5  6)

In [25]:
d={'a':[2,3,3,4,5],'b':[2,2,4,5,6]}
pd.DataFrame(d,index=d['a'])

a  b
2  2  2
3  3  2
3  3  4
4  4  5
5  5  6

In [26]:
d={'a':[2,3,3,4,5],'b':[2,2,4,5,6]}
pd.DataFrame(d,index=d['a']).info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 2 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       5 non-null      int64
 1   b       5 non-null      int64
dtypes: int64(2)
memory usage: 120.0 bytes


In [27]:
d={'a':[2,3,3,4,5],'b':[2,2,4,5,6]}
pd.DataFrame(d,index=d['a']).append((1,6))

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
d={'a':[2,3,3,4,5],'b':[2,2,4,5,6]}
pd.DataFrame(d,index=d['a']).append((1,6))